name: Tests
on: push
jobs:
  phpunit:
    name: PHPUnit on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '5.6', '7.0' , '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
      - name: Get Composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer update
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --bootstrap=tests/bootstrap.php --no-coverage tests
